version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/github-action-test
permissions:
  - object: /home/ec2-user/github-action-test
    owner: ec2-user
    group: ec2-user
    mode: 755
